aliases:
  - &restore-npm-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    name: Restoring node_modules cache
  - &save-npm-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    name: Saving node_modules cache
    paths:
      - node_modules

defaults: &defaults
  working_directory: /home/circleci/repo
  docker:
    - image: circleci/node:14

version: 2.1
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Install Node modules
          command: yarn
      - save_cache: *save-npm-cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Build Blog
          command: yarn build
      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - public

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - attach_workspace:
          at: /home/circleci/repo
      - run:
          name: Disable jekyll builds
          command: touch /home/circleci/repo/public/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "mitchellsimoens@gmail.com"
            git config user.name "mitchellsimoens"
      - add_ssh_keys:
          fingerprints:
            - "01:19:71:d8:d5:e9:f2:fd:75:ba:dc:b5:e1:6c:cc:99"
      - run:
          name: Deploy Blog
          # need --git for this bug: https://github.com/tschaub/gh-pages/issues/308
          command: yarn gh-pages --dotfiles --message "[skip ci] Updates" --dist public --git $(which git)
      - run:
          name: Invalidate Cloudflare Cache
          command: |
            curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "Authorization: Bearer $CLOUDFLARE_AUTH_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}'

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: ESLint
          command: yarn lint

  type-check:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: TypeScript Type Check
          command: yarn type-check

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      # - type-check:
      #     requires:
      #       - install-dependencies
      - build:
          requires:
            - lint
            # - type-check
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
