aliases:
  - &restore-npm-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    name: Restoring node_modules cache
  - &save-npm-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    name: Saving node_modules cache
    paths:
      - node_modules

defaults: &defaults
  working_directory: /home/circleci/repo
  docker:
    - image: circleci/node:12

version: 2.1
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Install Node modules
          command: yarn
      - save_cache: *save-npm-cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Build Blog
          command: yarn build
      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - public

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/repo
      - run:
          name: Disable jekyll builds
          command: touch /home/circleci/repo/public/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "mitchellsimoens@gmail.com"
            git config user.name "mitchellsimoens"
      - add_ssh_keys:
          fingerprints:
            - "01:19:71:d8:d5:e9:f2:fd:75:ba:dc:b5:e1:6c:cc:99"
      - run:
          name: Deploy Blog
          command: yarn deploy

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
