name: Lint

on: push

jobs:
  master:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
